version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: 'root@172.21.190.189:/data/wordpress'
      password: 'Aa123456_'
      allow_other: ''
  db:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: 'root@172.21.190.189:/data/mysql'
      password: 'Aa123456_'
      allow_other: ''